# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'traefik'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['<SERVER_IP>:8080']

# List of Consul service discovery configurations.
  - job_name: node-exporter
    scrape_interval: 15s
    honor_labels: true
    consul_sd_configs:
    - server: <SERVER_IP>:8500
      services: [node-exporter]
    relabel_configs:
    - source_labels: [__meta_consul_tags]
      regex: .*,_app=([^,]+),.*
      replacement: ${1}
      target_label: _app
    - source_labels: [__meta_consul_tags]
      regex: .*,_service=([^,]+),.*
      replacement: ${1}
      target_label: _service
    - source_labels: [__meta_consul_tags]
      regex: .*,_hostname=([^,]+),.*
      replacement: ${1}
      target_label: _hostname
    - source_labels: [__meta_consul_tags]
      regex: .*,_environment=([^,]+),.*
      replacement: ${1}
      target_label: _environment

  - job_name: 'nomad_metrics'

    consul_sd_configs:
    - server: '<SERVER_IP>:8500'
      services: ['nomad-clients', 'nomad-servers']

    relabel_configs:
    - source_labels: ['__meta_consul_tags']
      regex: '(.*)http(.*)'
      action: keep

    scrape_interval: 5s
    metrics_path: /v1/metrics
    params:
      format: ['prometheus']

  - job_name: 'unifipoller'
    scrape_interval: 30s
    static_configs:
    - targets: ['unifipoller.service.<LOCAL_DOMAIN>']

  - job_name: 'pihole01'
    scrape_interval: 30s
    static_configs:
      - targets: ['<PIHOLE_1_IP>:9617']

  - job_name: 'pihole02'
    scrape_interval: 30s
    static_configs:
      - targets: ['<PIHOLE_2_IP>:9617']
